name: Runs All Unit tests

on:
  push:
    branches:
      - '**'
  # pull_request:
  #   branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v3
      - name: Enable corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Execute Unit tests
        run: pnpm install --frozen-lockfile && pnpm test --run
